# Generated by Django 5.0.3 on 2024-03-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='id',
            new_name='new_id',
        ),
    ]
